require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RideStatesController do

  # This should return the minimal set of attributes required to create a valid
  # RideState. As you add validations to RideState, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "ride" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RideStatesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all ride_states as @ride_states" do
      ride_state = RideState.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ride_states).should eq([ride_state])
    end
  end

  describe "GET show" do
    it "assigns the requested ride_state as @ride_state" do
      ride_state = RideState.create! valid_attributes
      get :show, {:id => ride_state.to_param}, valid_session
      assigns(:ride_state).should eq(ride_state)
    end
  end

  describe "GET new" do
    it "assigns a new ride_state as @ride_state" do
      get :new, {}, valid_session
      assigns(:ride_state).should be_a_new(RideState)
    end
  end

  describe "GET edit" do
    it "assigns the requested ride_state as @ride_state" do
      ride_state = RideState.create! valid_attributes
      get :edit, {:id => ride_state.to_param}, valid_session
      assigns(:ride_state).should eq(ride_state)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RideState" do
        expect {
          post :create, {:ride_state => valid_attributes}, valid_session
        }.to change(RideState, :count).by(1)
      end

      it "assigns a newly created ride_state as @ride_state" do
        post :create, {:ride_state => valid_attributes}, valid_session
        assigns(:ride_state).should be_a(RideState)
        assigns(:ride_state).should be_persisted
      end

      it "redirects to the created ride_state" do
        post :create, {:ride_state => valid_attributes}, valid_session
        response.should redirect_to(RideState.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ride_state as @ride_state" do
        # Trigger the behavior that occurs when invalid params are submitted
        RideState.any_instance.stub(:save).and_return(false)
        post :create, {:ride_state => { "ride" => "invalid value" }}, valid_session
        assigns(:ride_state).should be_a_new(RideState)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RideState.any_instance.stub(:save).and_return(false)
        post :create, {:ride_state => { "ride" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ride_state" do
        ride_state = RideState.create! valid_attributes
        # Assuming there are no other ride_states in the database, this
        # specifies that the RideState created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RideState.any_instance.should_receive(:update_attributes).with({ "ride" => "" })
        put :update, {:id => ride_state.to_param, :ride_state => { "ride" => "" }}, valid_session
      end

      it "assigns the requested ride_state as @ride_state" do
        ride_state = RideState.create! valid_attributes
        put :update, {:id => ride_state.to_param, :ride_state => valid_attributes}, valid_session
        assigns(:ride_state).should eq(ride_state)
      end

      it "redirects to the ride_state" do
        ride_state = RideState.create! valid_attributes
        put :update, {:id => ride_state.to_param, :ride_state => valid_attributes}, valid_session
        response.should redirect_to(ride_state)
      end
    end

    describe "with invalid params" do
      it "assigns the ride_state as @ride_state" do
        ride_state = RideState.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RideState.any_instance.stub(:save).and_return(false)
        put :update, {:id => ride_state.to_param, :ride_state => { "ride" => "invalid value" }}, valid_session
        assigns(:ride_state).should eq(ride_state)
      end

      it "re-renders the 'edit' template" do
        ride_state = RideState.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RideState.any_instance.stub(:save).and_return(false)
        put :update, {:id => ride_state.to_param, :ride_state => { "ride" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ride_state" do
      ride_state = RideState.create! valid_attributes
      expect {
        delete :destroy, {:id => ride_state.to_param}, valid_session
      }.to change(RideState, :count).by(-1)
    end

    it "redirects to the ride_states list" do
      ride_state = RideState.create! valid_attributes
      delete :destroy, {:id => ride_state.to_param}, valid_session
      response.should redirect_to(ride_states_url)
    end
  end

end
